### ISSUE TITLE
Changing color mode panics

### ISSUE THREAD

**Issue by brofrain** [Synphonyte/leptos-use#19]
Hello,
changing a color mode using `use_color_mode` causes a panic for me.
I have prepared a simple reproduction app.

Cargo.toml:
```toml
[package]
name = "app"
version = "0.0.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.5.0-alpha2", features = ["csr", "nightly"] }
leptos-use = { git = "https://github.com/Synphonyte/leptos-use.git", rev = "075b073", features = [
  "storage",
] }
```

main.rs:
```rust
use leptos::*;
use leptos_use::{use_color_mode, ColorMode, UseColorModeReturn};

#[component]
fn App() -> impl IntoView {
    let UseColorModeReturn { mode, set_mode, .. } = use_color_mode();

    let toggle_dark = move |_| {
        set_mode(if mode() == ColorMode::Dark {
            ColorMode::Light
        } else {
            ColorMode::Dark
        });
    };

    view! {
        <div>
            <button on:click=toggle_dark>"Toggle dark"</button>
        </div>
    }
}

fn main() {
    std::panic::set_hook(Box::new(console_error_panic_hook::hook));
    leptos::mount_to_body(|| view! { <App/> })
}
```

![image](https://github.com/Synphonyte/leptos-use/assets/57999434/023fc8aa-27c3-48d3-bf8e-18c86774734f)

Additional context:
- feature "storage" must be present for the problem to occur
- only changing color mode (dark -> light / light -> dark) triggers the panic
- appears in both dev and release profile
- Trunk was used to run the code above in case that matters :)
